ARG PLEX_BASE_VERSION
FROM ghcr.io/constructorfleet/mcp-plex:${PLEX_BASE_VERSION}

WORKDIR /app

ENTRYPOINT ["/app/plex/entrypoint.service.sh"]

ENV SCRIPT="load-data"
ENV PLEX_TOKEN=
ENV PLEX_URL=
# ENV MCP_EXTRA_ARGS="--plex-token $$PLEX_TOKEN --plex-url $$PLEX_URL"
ENV PROJECT_ROOT="/app"
