[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-plex"
version = "0.7.3"
description = "Plex-specific automation"
requires-python = ">=3.11,<4"
dependencies = [
  "httpx>=0.28.1",
  "mcp_base @ file://${PROJECT_ROOT}/base",
  "plexapi>=4.17.0",
  "rapidfuzz>=3.13.0",
]

[project.scripts]
mcp-plex = "plex.server:main"

[tool.setuptools]
package-dir = { "" = "../src" }

[tool.setuptools.packages.find]
where = ["../src"]
include = ["plex"]
